Repository gardener/component-cli, pull requests merged in 2021-06, with the labels that each got.

#12 fix typo components-cli to component-cli
  .reuse/dep5
  README.md
  cmd/component-cli/app/app.go
  docs/README.md
  docs/reference/component-cli.md
  docs/reference/component-cli_component-archive.md
  docs/reference/component-cli_component-archive_component-references.md
  docs/reference/component-cli_component-archive_component-references_add.md
  docs/reference/component-cli_component-archive_create.md
  docs/reference/component-cli_component-archive_export.md
  docs/reference/component-cli_component-archive_remote.md
  docs/reference/component-cli_component-archive_remote_get.md
  docs/reference/component-cli_component-archive_remote_push.md
  docs/reference/component-cli_component-archive_resources.md
  docs/reference/component-cli_component-archive_resources_add.md
  docs/reference/component-cli_component-archive_sources.md
  docs/reference/component-cli_component-archive_sources_add.md
  docs/reference/component-cli_ctf.md
  docs/reference/component-cli_ctf_add.md
  docs/reference/component-cli_ctf_push.md
  docs/reference/component-cli_image-vector.md
  docs/reference/component-cli_image-vector_add.md
  docs/reference/component-cli_image-vector_generate-overwrite.md
  docs/reference/component-cli_oci.md
  docs/reference/component-cli_oci_copy.md
  docs/reference/component-cli_oci_pull.md
  docs/reference/component-cli_oci_repositories.md
  docs/reference/component-cli_oci_tags.md
  docs/reference/component-cli_version.md
  docs/reference/components-cli_component-archive_remote_get.md
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#13 update component-spec to 0.0.40
  go.mod
  go.sum
  ociclient/cache/cache_suite_test.go
  ociclient/client_test.go
  ociclient/credentials/builder.go
  ociclient/credentials/keyring_test.go
  pkg/commands/componentarchive/componentarchive_test.go
  pkg/commands/componentarchive/componentreferences/add_test.go
  pkg/commands/componentarchive/remote/get.go
  pkg/commands/componentarchive/resources/add_test.go
  pkg/commands/componentarchive/sources/add_test.go
  pkg/commands/ctf/add_test.go
  pkg/commands/imagevector/add_test.go
  pkg/commands/imagevector/generateoverwrite.go
  pkg/commands/imagevector/generateoverwrite_test.go
  pkg/components/localcache.go
  pkg/components/localcache_suite_test.go
  pkg/components/utils.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/accesstypes.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/cdutils/utils.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/componentdescriptor.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/default.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/helper.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/list.go
  vendor/github.com/gardener/component-spec/bindings-go/ctf/componentarchive.go
  vendor/github.com/gardener/component-spec/bindings-go/ctf/ctf.go
  vendor/github.com/gardener/component-spec/bindings-go/ctf/ctfutils/ctfutils.go
  vendor/github.com/gardener/component-spec/bindings-go/oci/resolve.go
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/testing/null.go
  vendor/github.com/mandelsoft/vfs/pkg/osfs/osfs_unix.go
  vendor/github.com/mandelsoft/vfs/pkg/osfs/osfs_windows.go
  vendor/github.com/mandelsoft/vfs/pkg/vfs/errors_unix.go
  vendor/github.com/mandelsoft/vfs/pkg/vfs/errors_windows.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#16 implement integration tests for pushing a ctf to a registry
  ociclient/test/envtest/envtest.go
  pkg/commands/ctf/ctf_suite_test.go
  pkg/commands/ctf/push.go
  pkg/commands/ctf/push_test.go
Labels: needs/ok-to-test, needs/review, size/m

#17 Fix: componentarchive remote push
  pkg/commands/componentarchive/remote/push.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#18 examples revised version
  docs/README.md
  docs/reference/component-cli_component-archive_component-references_add.md
  pkg/commands/componentarchive/componentreferences/add.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s
