Repository gardener/component-cli, pull requests merged in 2022-05, with the labels that each got.

#78 Update to alpine:3.15
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#81 remove build date variable from install script
  hack/install.sh
Labels: needs/ok-to-test, needs/review, size/xs

#83 Upgrade go to 1.18
  go.mod
  go.sum
  vendor/github.com/Masterminds/semver/v3/go.mod
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/drone/envsubst/go.mod
  vendor/github.com/drone/envsubst/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/zapr/go.mod
  vendor/github.com/go-task/slim-sprig/go.mod
  vendor/github.com/go-task/slim-sprig/go.sum
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/moby/locker/go.mod
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.sum
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#82 Add cd validation call for component archive creation
  pkg/componentarchive/archive.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#84 ca create better validation for missing paramters
  pkg/commands/componentarchive/create.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
